### ISSUE TITLE
make svg_fmt an optional dependency?

### ISSUE THREAD

**Issue by wez** [nical/guillotiere#21]
Would you be open to adding a feature to control whether that dependency is included?

**Comment by nical** [comment]
Hi, `svg_fmt` is really tiny. It isn't worth adding a feature flag for.

**Comment by wez** [comment]
It's not the size so much as it being an additional crate that needs to be downloaded; each additional dependency can increase the flakiness due to network "burps".

I totally get it if you don't want to add a flag for this, just wanted to share that my initial reaction to using this crate was "wtf is SVG doing in here?" and then "how do I turn that off?".

It's probably just a couple of lines to add a feature flag and then you can dodge future discussions :)

**Comment by nical** [comment]
Yeah, don't worry. svg_fmt is jus a few `Debug` impls so that `println!("{:?}", rectangle(0,1,2,3))` prints `<rect x="0" y="1" width="2" height="3" ry="0"`. Nothing dramatic like any kind of real svg functionality.

There actually used to be a feature flag and I removed it because it was getting in the way.
